# Generated by Django 5.0.2 on 2024-03-13 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "hotel_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("contact", models.IntegerField()),
                ("free_wifi", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                ("spa", models.BooleanField(default=False)),
                ("gym", models.BooleanField(default=False)),
                ("restaurant", models.BooleanField(default=False)),
                ("laundry", models.BooleanField(default=False)),
                ("stars", models.IntegerField(default=1)),
                ("overview", models.TextField(default="")),
                ("nearby", models.TextField(default="")),
                ("checkin_time", models.TimeField()),
                ("checkout_time", models.TimeField()),
            ],
        ),
    ]
