# Generated by Django 5.0.2 on 2024-03-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_created_review_created_at_remove_review_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
